spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cafe_reservation}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1111}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET:c2VjcmV0LWtleS1mb3ItY2FmZS1yZXNlcnZhdGlvbi1jaGFuZ2UtbWUtaW4tcHJvZA==}
      expiration-ms: 86400000
